### PR TITLE
feat: upgrade luajit to 2.1.0-beta3

### PR DESCRIPTION
**Pull request by perrin4869**
I was running `neovim` from the `slackers` repo, but I kept encountering random `PANIC: unprotected error in call to Lua API (not enough memory)` errors followed by `neovim` crashing... I tracked it down to a [`luajit` limitation](https://stackoverflow.com/questions/35155444/why-is-luajits-memory-limited-to-1-2-gb-on-64-bit-platforms).

I noticed that the official `neovim` logs show it is built against `luajit@2.1.0-beta3`, for example: https://github.com/neovim/neovim/releases/tag/v0.8.3 (notice the banner on top).

I updated `luajit` here and rebuilt `neovim` and the problem seems to be resolved

### CODE REVIEW

**Comment by perrin4869** [comment]
I have been using this for the past month or so, and all issues I had with neovim crashing due to the error above are gone

**Comment by conraid** [comment]
Sorry for the delay, I'm not getting notifications or emails :/
I don't have this error, can you give me an example where it appears and how to recreate it?
Updating luajit to beta I could, but I need to check first if it doesn't cause problems for other packages that need luajit

Thanks for the report

**Comment by perrin4869** [comment]
thanks for getting back!
it's tough to say how to reproduce, I'm imagining that you'd need to load many plugins to where non-beta luajit runs out of memory (it seems as of 2.0.5, there was a 1GB memory limit).
you can try loading my `neovim` config from [here](https://github.com/perrin4869/dotfiles) and try editing typescript files, and you're likely to run into a crash... but that would be a pain to setup I think 😅

hm... did you rebuild neovim after installing the beta luajit?

**Comment by conraid** [comment]
In the next update there will be luajit beta. Let me know if everything is OK.

**Comment by perrin4869** [comment]
nice, just upgraded to the new packages, it's working fine thus far! I'll close this PR, I don't expect any further errors, thanks!

**Pull request closed without merging**
